######################################################
# MSDS434 - Section 55 - Winter '25
# Module 10: Github actions CI/CD demonstration
# 
# Kevin Geidel
# 
# ci.yml - Execute commands from a Github container
######################################################

name: CI

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo CI/CD is running!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Here is a more complex...
          echo set of instructions...
          date